if(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(ARCH_NAME "Win64")
endif()

if(CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
    set(CMAKE_GENERATOR_PLATFORM "Win64" CACHE STRING "" FORCE)
endif()