name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: windows-latest

        steps:

        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x

        - name: Restore
          run: dotnet restore
           
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v2

        - name: Install CMake
          uses: ssrobins/install-cmake@v1
          with:
           version: 4.0.3

        - name: Generate solution
          run: .\Generate.bat

        - name: Build
          run: msbuild Intermediate\Win64\UOEngine.sln /p:Configuration=Development /p:Platform=x64 /m /verbosity:minimal
