name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: windows-latest

        steps:

        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 10.0.x
           
        - name: Restore
          run: dotnet restore UOEngine.slnx

        - name: Build
          run: dotnet build UOEngine.slnx --configuration Development --no-restore -p:Platform=x64
