name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: windows-latest

        steps:

        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 10.0.x
           
        - name: Restore
          run: dotnet restore UOEngine.slnx --configfile NuGet.Config -p:Configuration=Release -p:Platform=x64

        - name: Build Editor
          run: dotnet build Source\Editor\UOEngine.Editor\UOEngine.Editor.csproj --configuration Release --no-restore -p:Platform=x64 -m:1
