name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: windows-latest

        steps:

        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
            include-prerelease: false
           
        - name: Generate solution
          run: Generate.bat

        #- name: Build
        #  run:
